### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Solaris-developer** [XtramCZ/auto-advertise-js#17]
```yaml
Loading by DXRK
Bot running on http://localhost:3000
AxiosError: Request failed with status code 401
    at settle (/home/runner/ader-roi/node_modules/axios/dist/node/axios.cjs:1902:12)
    at IncomingMessage.handleStreamEnd (/home/runner/ader-roi/node_modules/axios/dist/node/axios.cjs:2954:11)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_BAD_REQUEST'```


using replit, using secrets, channel ids are valid

**Comment by XtramCZ** [comment]
Hi
401 usually means you have a non working token, please check it
otherwise, I don't have that much experience with replit to tell where's the problem

**Comment by Solaris-developer** [comment]
alright, thanks for the help.
