### ISSUE TITLE
The cooldown/slowmode problem is still there

### ISSUE THREAD

**Issue by Kephronic** [XtramCZ/auto-advertise-js#3]
Hi, i just tested the new fix what you made to the tool and basically the error is still being there and  is worst because now the tool just stop working and says this thing:

```
 > Logged in

 > Sending first batch of messages...
C:\Users\Administrator\Desktop\auto-advertise-js-main\node_modules\discord.js-selfbot-v13\src\rest\RequestHandler.js:432      throw new DiscordAPIError(data, res.status, request);
            ^

DiscordAPIError: Missing Permissions
    at RequestHandler.execute (C:\Users\Administrator\Desktop\auto-advertise-js-main\node_modules\discord.js-selfbot-v13\src\rest\RequestHandler.js:432:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RequestHandler.push (C:\Users\Administrator\Desktop\auto-advertise-js-main\node_modules\discord.js-selfbot-v13\src\rest\RequestHandler.js:80:14)
    at async TextChannel.send (C:\Users\Administrator\Desktop\auto-advertise-js-main\node_modules\discord.js-selfbot-v13\src\structures\interfaces\TextBasedChannel.js:217:15) {
  method: 'post',
  path: '/channels/754765995490672741/messages',
  code: 50013,
  httpStatus: 403,
  captcha: null,
  requestData: {
    json: {
      activity: undefined,
      content: 'test',
      tts: false,
      nonce: undefined,
      embeds: undefined,
      components: undefined,
      username: undefined,
      avatar_url: undefined,
      allowed_mentions: undefined,
      flags: undefined,
      message_reference: undefined,
      attachments: undefined,
      sticker_ids: undefined,
      thread_name: undefined
    },
    files: []
  },
  retries: 0
}

Node.js v19.8.1

C:\Users\Administrator\Desktop\auto-advertise-js-main>pause
Press any key to continue . . .
```

And now it says the same thing when you try to send a message in any server where you got muted, timeout or just with slowmode/cooldown activated.

**Comment by XtramCZ** [comment]
Hi, I was able to replicate the issue, but only when you are muted. Otherwise it works with no error.

**Comment by XtramCZ** [comment]
I uploaded a new version, can you please test it?
